export type Scope3ViewMode = "operational" | "upstream_downstream";

export type Scope3Category = {
    id: number;
    code: string; // e.g. "Cat 1"
    name: string;
    description: string;
    slug: string;
    type: "upstream" | "downstream";
    isImplemented: boolean;
    
    // View 1 (Operational vs Product Focus) Grouping
    view1Group: "Corporate & Operations" | "Supply Chain & Goods" | "Product Lifecycle" | "Business Model";
    
    // View 2 (Basic Upstream vs Downstream) Section & Subgroup
    view2Section: "Upstream (Supply Chain)" | "Downstream (Product & Market)";
    view2Subgroup: 
        | "Procurement & Assets"
        | "Logistics & Energy"
        | "Workforce & Waste"
        | "Product Use Phase"
        | "Logistics & Expansion"
        | "Finance";

    emissionsTco2e: number;
    sharePercent: number;
    trendPercent: number; // e.g. +3.2 or -1.5
    trendDirection: "up" | "down" | "flat";
    spendUsd: number;
    dataCoveragePercent: number;
    methodology: "Spend-Based" | "Average Data" | "Supplier Specific" | "Hybrid Activity";
    icon: string;
    status: "Verified" | "Audited" | "Estimated" | "Pending Review";
};

export const SCOPE3_CATEGORIES: Scope3Category[] = [
    // ------------------- IMPLEMENTED CATEGORIES (1, 2, 3, 4, 5, 6, 7, 9, 15) -------------------
    {
        id: 1,
        code: "Cat 1",
        name: "Purchased Goods & Services",
        description: "Extraction, production, and transportation of goods and services purchased or acquired.",
        slug: "category-1",
        type: "upstream",
        isImplemented: true,
        view1Group: "Supply Chain & Goods",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Procurement & Assets",
        emissionsTco2e: 18420.5,
        sharePercent: 53.9,
        trendPercent: 4.8,
        trendDirection: "up",
        spendUsd: 14250000,
        dataCoveragePercent: 96.2,
        methodology: "Spend-Based",
        icon: "shopping_cart",
        status: "Verified",
    },
    {
        id: 2,
        code: "Cat 2",
        name: "Capital Goods",
        description: "Final goods that have an extended life and are used to manufacture products or provide services.",
        slug: "category-2",
        type: "upstream",
        isImplemented: true,
        view1Group: "Corporate & Operations",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Procurement & Assets",
        emissionsTco2e: 4150.2,
        sharePercent: 12.1,
        trendPercent: 8.2,
        trendDirection: "up",
        spendUsd: 5400000,
        dataCoveragePercent: 94.0,
        methodology: "Spend-Based",
        icon: "precision_manufacturing",
        status: "Verified",
    },
    {
        id: 3,
        code: "Cat 3",
        name: "Fuel & Energy Activities",
        description: "Extraction, production, and transportation of fuels and energy purchased (WTT & T&D losses).",
        slug: "category-3",
        type: "upstream",
        isImplemented: true,
        view1Group: "Corporate & Operations",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Logistics & Energy",
        emissionsTco2e: 2890.4,
        sharePercent: 8.5,
        trendPercent: -3.4,
        trendDirection: "down",
        spendUsd: 2100000,
        dataCoveragePercent: 98.5,
        methodology: "Average Data",
        icon: "bolt",
        status: "Audited",
    },
    {
        id: 4,
        code: "Cat 4",
        name: "Upstream Transport & Distribution",
        description: "Transportation & distribution services purchased by reporting company via DEFRA weight-distance protocol.",
        slug: "category-4",
        type: "upstream",
        isImplemented: true,
        view1Group: "Supply Chain & Goods",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Logistics & Energy",
        emissionsTco2e: 3120.8,
        sharePercent: 9.1,
        trendPercent: -2.1,
        trendDirection: "down",
        spendUsd: 3890000,
        dataCoveragePercent: 91.5,
        methodology: "Hybrid Activity",
        icon: "local_shipping",
        status: "Audited",
    },
    {
        id: 5,
        code: "Cat 5",
        name: "Waste from Operations",
        description: "Disposal and treatment of waste generated in reporting company's operations.",
        slug: "category-5",
        type: "upstream",
        isImplemented: true,
        view1Group: "Corporate & Operations",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Workforce & Waste",
        emissionsTco2e: 640.1,
        sharePercent: 1.9,
        trendPercent: -5.2,
        trendDirection: "down",
        spendUsd: 420000,
        dataCoveragePercent: 95.0,
        methodology: "Average Data",
        icon: "delete_sweep",
        status: "Verified",
    },
    {
        id: 6,
        code: "Cat 6",
        name: "Business Travel",
        description: "Transportation of employees for business-related activities in non-company vehicles.",
        slug: "category-6",
        type: "upstream",
        isImplemented: true,
        view1Group: "Corporate & Operations",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Workforce & Waste",
        emissionsTco2e: 1180.6,
        sharePercent: 3.5,
        trendPercent: 12.4,
        trendDirection: "up",
        spendUsd: 1850000,
        dataCoveragePercent: 99.0,
        methodology: "Hybrid Activity",
        icon: "flight_takeoff",
        status: "Verified",
    },
    {
        id: 7,
        code: "Cat 7",
        name: "Employee Commuting",
        description: "Transportation of employees between home and worksites, including transit & personal vehicles.",
        slug: "category-7",
        type: "upstream",
        isImplemented: true,
        view1Group: "Corporate & Operations",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Workforce & Waste",
        emissionsTco2e: 840.3,
        sharePercent: 2.5,
        trendPercent: 1.1,
        trendDirection: "up",
        spendUsd: 950000,
        dataCoveragePercent: 82.0,
        methodology: "Average Data",
        icon: "commute",
        status: "Estimated",
    },
    {
        id: 9,
        code: "Cat 9",
        name: "Downstream Transport & Distribution",
        description: "Downstream transportation & product distribution logistics via DEFRA weight-distance protocol.",
        slug: "category-9",
        type: "downstream",
        isImplemented: true,
        view1Group: "Product Lifecycle",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Logistics & Expansion",
        emissionsTco2e: 2650.0,
        sharePercent: 7.7,
        trendPercent: 2.3,
        trendDirection: "up",
        spendUsd: 3100000,
        dataCoveragePercent: 89.0,
        methodology: "Hybrid Activity",
        icon: "package_2",
        status: "Verified",
    },
    {
        id: 15,
        code: "Cat 15",
        name: "Investments (Financed)",
        description: "Financed Scope 1, 2 & 3 emissions calculated via PCAF attribution factors.",
        slug: "category-15",
        type: "downstream",
        isImplemented: true,
        view1Group: "Business Model",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Finance",
        emissionsTco2e: 250.0,
        sharePercent: 0.7,
        trendPercent: -8.4,
        trendDirection: "down",
        spendUsd: 15000000,
        dataCoveragePercent: 95.5,
        methodology: "Hybrid Activity",
        icon: "account_balance",
        status: "Verified",
    },

    // ------------------- UNIMPLEMENTED CATEGORIES (FILTERED OUT IN UI) -------------------
    {
        id: 8,
        code: "Cat 8",
        name: "Upstream Leased Assets",
        description: "Operation of assets leased by reporting company not included in Scope 1 or Scope 2.",
        slug: "category-8",
        type: "upstream",
        isImplemented: false,
        view1Group: "Supply Chain & Goods",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Procurement & Assets",
        emissionsTco2e: 0,
        sharePercent: 0,
        trendPercent: 0,
        trendDirection: "flat",
        spendUsd: 0,
        dataCoveragePercent: 0,
        methodology: "Average Data",
        icon: "real_estate_agent",
        status: "Estimated",
    },
    {
        id: 10,
        code: "Cat 10",
        name: "Processing of Sold Products",
        description: "Processing of intermediate products sold by third party manufacturers.",
        slug: "category-10",
        type: "downstream",
        isImplemented: false,
        view1Group: "Product Lifecycle",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Product Use Phase",
        emissionsTco2e: 0,
        sharePercent: 0,
        trendPercent: 0,
        trendDirection: "flat",
        spendUsd: 0,
        dataCoveragePercent: 0,
        methodology: "Average Data",
        icon: "settings_suggest",
        status: "Estimated",
    },
    {
        id: 11,
        code: "Cat 11",
        name: "Use of Sold Products",
        description: "End-use of goods and services sold by reporting company over lifetime.",
        slug: "category-11",
        type: "downstream",
        isImplemented: false,
        view1Group: "Product Lifecycle",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Product Use Phase",
        emissionsTco2e: 0,
        sharePercent: 0,
        trendPercent: 0,
        trendDirection: "flat",
        spendUsd: 0,
        dataCoveragePercent: 0,
        methodology: "Hybrid Activity",
        icon: "power",
        status: "Estimated",
    },
    {
        id: 12,
        code: "Cat 12",
        name: "End-of-Life Treatment of Sold Products",
        description: "Waste disposal and treatment of products sold at end of life.",
        slug: "category-12",
        type: "downstream",
        isImplemented: false,
        view1Group: "Product Lifecycle",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Product Use Phase",
        emissionsTco2e: 0,
        sharePercent: 0,
        trendPercent: 0,
        trendDirection: "flat",
        spendUsd: 0,
        dataCoveragePercent: 0,
        methodology: "Average Data",
        icon: "recycling",
        status: "Estimated",
    },
    {
        id: 13,
        code: "Cat 13",
        name: "Downstream Leased Assets",
        description: "Operation of assets owned by reporting company and leased to third parties.",
        slug: "category-13",
        type: "downstream",
        isImplemented: false,
        view1Group: "Business Model",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Logistics & Expansion",
        emissionsTco2e: 0,
        sharePercent: 0,
        trendPercent: 0,
        trendDirection: "flat",
        spendUsd: 0,
        dataCoveragePercent: 0,
        methodology: "Supplier Specific",
        icon: "domain_disabled",
        status: "Estimated",
    },
    {
        id: 14,
        code: "Cat 14",
        name: "Franchises",
        description: "Operation of franchises in reporting year.",
        slug: "category-14",
        type: "downstream",
        isImplemented: false,
        view1Group: "Business Model",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Logistics & Expansion",
        emissionsTco2e: 0,
        sharePercent: 0,
        trendPercent: 0,
        trendDirection: "flat",
        spendUsd: 0,
        dataCoveragePercent: 0,
        methodology: "Average Data",
        icon: "storefront",
        status: "Estimated",
    },
];

export const SCOPE3_SUMMARY = {
    totalEmissionsTco2e: 34142.9,
    upstreamEmissionsTco2e: 31242.9,
    downstreamEmissionsTco2e: 2900.0,
    upstreamSharePercent: 91.5,
    downstreamSharePercent: 8.5,
    yoyChangePercent: 3.8,
    overallCoveragePercent: 95.4,
    trackedCategoriesCount: 9,
    verifiedSpendUsd: 46960000,
};

export const SCOPE3_TREND_DATA = [
    { month: "Jan", upstream: 2450, downstream: 220, total: 2670 },
    { month: "Feb", upstream: 2510, downstream: 230, total: 2740 },
    { month: "Mar", upstream: 2680, downstream: 245, total: 2925 },
    { month: "Apr", upstream: 2590, downstream: 230, total: 2820 },
    { month: "May", upstream: 2720, downstream: 250, total: 2970 },
    { month: "Jun", upstream: 2640, downstream: 240, total: 2880 },
    { month: "Jul", upstream: 2780, downstream: 260, total: 3040 },
    { month: "Aug", upstream: 2810, downstream: 255, total: 3065 },
    { month: "Sep", upstream: 2690, downstream: 240, total: 2930 },
    { month: "Oct", upstream: 2550, downstream: 230, total: 2780 },
    { month: "Nov", upstream: 2420, downstream: 210, total: 2635 },
    { month: "Dec", upstream: 2400, downstream: 205, total: 2605 },
];

export const VENDOR_HOTSPOTS = [
    {
        id: "v-1",
        vendorName: "Apex Logistics Global",
        category: "Cat 4: Upstream Freight",
        spend: "$1,840,000",
        emissions: "1,420.2 tCO2e",
        intensity: "0.77 kgCO2e/$",
        dataQuality: "DEFRA HGV Factor",
        status: "High Impact",
    },
    {
        id: "v-2",
        vendorName: "Titanium Metalwork Corp",
        category: "Cat 1: Purchased Raw Goods",
        spend: "$4,120,000",
        emissions: "5,840.6 tCO2e",
        intensity: "1.41 kgCO2e/$",
        dataQuality: "Hybrid Spend/Mass",
        status: "Action Required",
    },
    {
        id: "v-3",
        vendorName: "Swift Distribution Logistics",
        category: "Cat 9: Downstream Last Mile",
        spend: "$1,950,000",
        emissions: "1,925.0 tCO2e",
        intensity: "0.98 kgCO2e/$",
        dataQuality: "DEFRA Van Model",
        status: "Verified",
    },
    {
        id: "v-4",
        vendorName: "Global PowerGrid Distribution",
        category: "Cat 3: T&D Energy Losses",
        spend: "$1,250,000",
        emissions: "1,890.0 tCO2e",
        intensity: "1.51 kgCO2e/$",
        dataQuality: "Grid Average",
        status: "Monitored",
    },
    {
        id: "v-5",
        vendorName: "GreenTech Energy Systems",
        category: "Cat 15: Clean Power Investment",
        spend: "$5,000,000",
        emissions: "250.0 tCO2e",
        intensity: "0.05 kgCO2e/$",
        dataQuality: "PCAF Standard",
        status: "Low Impact",
    },
];
