export type Scope3ViewMode = "operational" | "upstream_downstream";

export type Scope3Category = {
    id: number;
    code: string; // e.g. "Cat 1"
    name: string;
    description: string;
    slug: string;
    type: "upstream" | "downstream";
    
    // View 1 (Operational vs Product Focus) Grouping
    view1Group: "Corporate & Operations" | "Supply Chain & Goods" | "Product Lifecycle" | "Business Model";
    
    // View 2 (Basic Upstream vs Downstream) Section & Subgroup
    view2Section: "Upstream (Supply Chain)" | "Downstream (Product & Market)";
    view2Subgroup: 
        | "Procurement & Assets"
        | "Logistics & Energy"
        | "Workforce & Waste"
        | "Product Use Phase"
        | "Logistics & Expansion"
        | "Finance";

    emissionsTco2e: number;
    sharePercent: number;
    trendPercent: number; // e.g. +3.2 or -1.5
    trendDirection: "up" | "down" | "flat";
    spendUsd: number;
    dataCoveragePercent: number;
    methodology: "Spend-Based" | "Average Data" | "Supplier Specific" | "Hybrid Activity";
    icon: string;
    status: "Verified" | "Audited" | "Estimated" | "Pending Review";
};

export const SCOPE3_CATEGORIES: Scope3Category[] = [
    // ------------------- VIEW 1: SUPPLY CHAIN & GOODS -------------------
    {
        id: 1,
        code: "Cat 1",
        name: "Purchased Goods & Services",
        description: "Extraction, production, and transportation of goods and services purchased or acquired.",
        slug: "category-1",
        type: "upstream",
        view1Group: "Supply Chain & Goods",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Procurement & Assets",
        emissionsTco2e: 18420.5,
        sharePercent: 43.0,
        trendPercent: 4.8,
        trendDirection: "up",
        spendUsd: 14250000,
        dataCoveragePercent: 96.2,
        methodology: "Hybrid Activity",
        icon: "shopping_cart",
        status: "Verified",
    },
    {
        id: 4,
        code: "Cat 4",
        name: "Upstream Transport & Distribution",
        description: "Transportation & distribution services purchased by reporting company (tier 1 suppliers).",
        slug: "category-4",
        type: "upstream",
        view1Group: "Supply Chain & Goods",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Logistics & Energy",
        emissionsTco2e: 3120.8,
        sharePercent: 7.3,
        trendPercent: -2.1,
        trendDirection: "down",
        spendUsd: 3890000,
        dataCoveragePercent: 91.5,
        methodology: "Supplier Specific",
        icon: "local_shipping",
        status: "Audited",
    },
    {
        id: 8,
        code: "Cat 8",
        name: "Upstream Leased Assets",
        description: "Operation of assets leased by reporting company not included in Scope 1 or Scope 2.",
        slug: "category-8",
        type: "upstream",
        view1Group: "Supply Chain & Goods",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Procurement & Assets",
        emissionsTco2e: 420.3,
        sharePercent: 1.0,
        trendPercent: -0.5,
        trendDirection: "down",
        spendUsd: 650000,
        dataCoveragePercent: 88.0,
        methodology: "Average Data",
        icon: "real_estate_agent",
        status: "Verified",
    },

    // ------------------- VIEW 1: CORPORATE & OPERATIONS -------------------
    {
        id: 2,
        code: "Cat 2",
        name: "Capital Goods",
        description: "Final goods that have an extended life and are used to manufacture products or provide services.",
        slug: "category-2",
        type: "upstream",
        view1Group: "Corporate & Operations",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Procurement & Assets",
        emissionsTco2e: 4150.2,
        sharePercent: 9.7,
        trendPercent: 8.2,
        trendDirection: "up",
        spendUsd: 5400000,
        dataCoveragePercent: 94.0,
        methodology: "Spend-Based",
        icon: "precision_manufacturing",
        status: "Verified",
    },
    {
        id: 3,
        code: "Cat 3",
        name: "Fuel & Energy Activities",
        description: "Extraction, production, and transportation of fuels and energy purchased (WTT & T&D losses).",
        slug: "category-3",
        type: "upstream",
        view1Group: "Corporate & Operations",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Logistics & Energy",
        emissionsTco2e: 2890.4,
        sharePercent: 6.7,
        trendPercent: -3.4,
        trendDirection: "down",
        spendUsd: 2100000,
        dataCoveragePercent: 98.5,
        methodology: "Average Data",
        icon: "bolt",
        status: "Audited",
    },
    {
        id: 5,
        code: "Cat 5",
        name: "Waste from Operations",
        description: "Disposal and treatment of waste generated in reporting company's operations.",
        slug: "category-5",
        type: "upstream",
        view1Group: "Corporate & Operations",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Workforce & Waste",
        emissionsTco2e: 640.1,
        sharePercent: 1.5,
        trendPercent: -5.2,
        trendDirection: "down",
        spendUsd: 420000,
        dataCoveragePercent: 95.0,
        methodology: "Supplier Specific",
        icon: "delete_sweep",
        status: "Verified",
    },
    {
        id: 6,
        code: "Cat 6",
        name: "Business Travel",
        description: "Transportation of employees for business-related activities in vehicles not owned/operated by company.",
        slug: "category-6",
        type: "upstream",
        view1Group: "Corporate & Operations",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Workforce & Waste",
        emissionsTco2e: 1180.6,
        sharePercent: 2.8,
        trendPercent: 12.4,
        trendDirection: "up",
        spendUsd: 1850000,
        dataCoveragePercent: 99.0,
        methodology: "Hybrid Activity",
        icon: "flight_takeoff",
        status: "Verified",
    },
    {
        id: 7,
        code: "Cat 7",
        name: "Employee Commuting",
        description: "Transportation of employees between their homes and their worksites, including teleworking emissions.",
        slug: "category-7",
        type: "upstream",
        view1Group: "Corporate & Operations",
        view2Section: "Upstream (Supply Chain)",
        view2Subgroup: "Workforce & Waste",
        emissionsTco2e: 840.3,
        sharePercent: 2.0,
        trendPercent: 1.1,
        trendDirection: "up",
        spendUsd: 950000,
        dataCoveragePercent: 82.0,
        methodology: "Average Data",
        icon: "commute",
        status: "Estimated",
    },

    // ------------------- VIEW 1: PRODUCT LIFECYCLE -------------------
    {
        id: 9,
        code: "Cat 9",
        name: "Downstream Transport & Distribution",
        description: "Transportation and distribution of products sold in reporting year between operations and end consumer.",
        slug: "category-9",
        type: "downstream",
        view1Group: "Product Lifecycle",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Logistics & Expansion",
        emissionsTco2e: 2650.0,
        sharePercent: 6.2,
        trendPercent: 2.3,
        trendDirection: "up",
        spendUsd: 3100000,
        dataCoveragePercent: 89.0,
        methodology: "Spend-Based",
        icon: "package_2",
        status: "Verified",
    },
    {
        id: 10,
        code: "Cat 10",
        name: "Processing of Sold Products",
        description: "Processing of intermediate products sold in reporting year by third party manufacturers.",
        slug: "category-10",
        type: "downstream",
        view1Group: "Product Lifecycle",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Product Use Phase",
        emissionsTco2e: 1480.2,
        sharePercent: 3.5,
        trendPercent: -1.8,
        trendDirection: "down",
        spendUsd: 1900000,
        dataCoveragePercent: 78.0,
        methodology: "Average Data",
        icon: "settings_suggest",
        status: "Estimated",
    },
    {
        id: 11,
        code: "Cat 11",
        name: "Use of Sold Products",
        description: "End-use of goods and services sold by reporting company over their expected lifetime.",
        slug: "category-11",
        type: "downstream",
        view1Group: "Product Lifecycle",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Product Use Phase",
        emissionsTco2e: 5230.7,
        sharePercent: 12.2,
        trendPercent: -4.1,
        trendDirection: "down",
        spendUsd: 6200000,
        dataCoveragePercent: 86.5,
        methodology: "Hybrid Activity",
        icon: "power",
        status: "Audited",
    },
    {
        id: 12,
        code: "Cat 12",
        name: "End-of-Life Treatment of Sold Products",
        description: "Waste disposal and treatment of products sold by reporting company at the end of their life.",
        slug: "category-12",
        type: "downstream",
        view1Group: "Product Lifecycle",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Product Use Phase",
        emissionsTco2e: 1250.4,
        sharePercent: 2.9,
        trendPercent: -6.0,
        trendDirection: "down",
        spendUsd: 1100000,
        dataCoveragePercent: 84.0,
        methodology: "Average Data",
        icon: "recycling",
        status: "Verified",
    },

    // ------------------- VIEW 1: BUSINESS MODEL -------------------
    {
        id: 13,
        code: "Cat 13",
        name: "Downstream Leased Assets",
        description: "Operation of assets owned by reporting company and leased to third parties.",
        slug: "category-13",
        type: "downstream",
        view1Group: "Business Model",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Logistics & Expansion",
        emissionsTco2e: 310.2,
        sharePercent: 0.7,
        trendPercent: 0.0,
        trendDirection: "flat",
        spendUsd: 480000,
        dataCoveragePercent: 90.0,
        methodology: "Supplier Specific",
        icon: "domain_disabled",
        status: "Verified",
    },
    {
        id: 14,
        code: "Cat 14",
        name: "Franchises",
        description: "Operation of franchises in reporting year, not included in Scope 1 and Scope 2.",
        slug: "category-14",
        type: "downstream",
        view1Group: "Business Model",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Logistics & Expansion",
        emissionsTco2e: 480.6,
        sharePercent: 1.1,
        trendPercent: 3.5,
        trendDirection: "up",
        spendUsd: 720000,
        dataCoveragePercent: 92.0,
        methodology: "Average Data",
        icon: "storefront",
        status: "Audited",
    },
    {
        id: 15,
        code: "Cat 15",
        name: "Investments",
        description: "Operation of investments (including equity, debt, project finance) not included in Scope 1 or Scope 2.",
        slug: "category-15",
        type: "downstream",
        view1Group: "Business Model",
        view2Section: "Downstream (Product & Market)",
        view2Subgroup: "Finance",
        emissionsTco2e: 210.1,
        sharePercent: 0.5,
        trendPercent: -8.4,
        trendDirection: "down",
        spendUsd: 15000000,
        dataCoveragePercent: 95.5,
        methodology: "Hybrid Activity",
        icon: "account_balance",
        status: "Verified",
    },
];

export const SCOPE3_SUMMARY = {
    totalEmissionsTco2e: 42850.4,
    upstreamEmissionsTco2e: 31240.0,
    downstreamEmissionsTco2e: 11610.4,
    upstreamSharePercent: 72.9,
    downstreamSharePercent: 27.1,
    yoyChangePercent: 3.4,
    overallCoveragePercent: 94.8,
    trackedCategoriesCount: 15,
    verifiedSpendUsd: 59360000,
};

export const SCOPE3_TREND_DATA = [
    { month: "Jan", upstream: 2450, downstream: 920, total: 3370 },
    { month: "Feb", upstream: 2510, downstream: 940, total: 3450 },
    { month: "Mar", upstream: 2680, downstream: 980, total: 3660 },
    { month: "Apr", upstream: 2590, downstream: 960, total: 3550 },
    { month: "May", upstream: 2720, downstream: 1010, total: 3730 },
    { month: "Jun", upstream: 2640, downstream: 990, total: 3630 },
    { month: "Jul", upstream: 2780, downstream: 1040, total: 3820 },
    { month: "Aug", upstream: 2810, downstream: 1030, total: 3840 },
    { month: "Sep", upstream: 2690, downstream: 970, total: 3660 },
    { month: "Oct", upstream: 2550, downstream: 930, total: 3480 },
    { month: "Nov", upstream: 2420, downstream: 890, total: 3310 },
    { month: "Dec", upstream: 2400, downstream: 890, total: 3290 },
];

export const VENDOR_HOTSPOTS = [
    {
        id: "v-1",
        vendorName: "Apex Logistics Global",
        category: "Cat 4: Upstream Freight",
        spend: "$1,840,000",
        emissions: "1,420.2 tCO2e",
        intensity: "0.77 kgCO2e/$",
        dataQuality: "Tier 1 Verified",
        status: "High Impact",
    },
    {
        id: "v-2",
        vendorName: "Titanium Metalwork Corp",
        category: "Cat 1: Purchased Raw Goods",
        spend: "$4,120,000",
        emissions: "5,840.6 tCO2e",
        intensity: "1.41 kgCO2e/$",
        dataQuality: "Hybrid Spend/Mass",
        status: "Action Required",
    },
    {
        id: "v-3",
        vendorName: "EcoFreight Maritime",
        category: "Cat 4: Ocean Transport",
        spend: "$980,000",
        emissions: "860.4 tCO2e",
        intensity: "0.87 kgCO2e/$",
        dataQuality: "Supplier API",
        status: "On Track",
    },
    {
        id: "v-4",
        vendorName: "Global PowerGrid Distribution",
        category: "Cat 3: T&D Energy Losses",
        spend: "$1,250,000",
        emissions: "1,890.0 tCO2e",
        intensity: "1.51 kgCO2e/$",
        dataQuality: "Grid Average",
        status: "Monitored",
    },
    {
        id: "v-5",
        vendorName: "Lumina Data Services",
        category: "Cat 1: Cloud & IT Services",
        spend: "$740,000",
        emissions: "240.1 tCO2e",
        intensity: "0.32 kgCO2e/$",
        dataQuality: "RE100 Certified",
        status: "Low Impact",
    },
];
